services:
  docs:
    image: money_management_local_docs
    container_name: money_management_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./money_management:/app/money_management:z
    ports:
      - '9000:9000'
    command: /start-docs
